# Generated by Django 4.2.9 on 2024-03-25 08:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='role',
            field=models.CharField(choices=[('donor', 'Donor'), ('patient', 'Patient')], default='patient', max_length=20),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('fulfilled', 'Fulfilled')], default='pending', max_length=20),
        ),
    ]
